name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: pLabs5/.github/.github/workflows/build-payload.yml@main
    permissions:
      contents: write
    with:
      artifact-name: drpc5
      elf-path: dRPC5.elf
      artifact-paths: |
        dRPC5.elf
        dRPC5.elf.sha256
        dist/drpc5-tile.pkg
